config with terraform
oracle-devrel/oci-devops-examples pull request #10
Opened 2022-04-22 12:40 UTC by RahulMR42

# Description

Manage policies and dynamic group and more using OCI Devops and Terraform.
Demonstrate how to execute terraform scripts from OCI Build runner.
Manage Terraform state management using object storage.

Fixes # (issues)

New samples # (demos / Illustrations )

Centralized configuration management using terraform (policies and dgs)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

- [x] Free Tier
- [x] Always Free
- [x] Paid 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings.
- [x] All the sensitive informations are masked or removed.
- [x] All the links mentioned are valid and tested.
- [x] Image names are separated only with '-'.
- [x] Added instruction to clone only this sample and links to other common sample pages.

2022-04-22 12:41 UTC, RahulMR42 commented
recheck

2022-04-22 13:19 UTC, ashok-cm requested changes

2022-04-22 13:19 UTC, ashok-cm commented on oci-config-examples/oci_devops_policy_dg_terraform/README.md
> +![](images/oci_project.png)
we may mask customer's name.

2022-04-22 13:19 UTC, ashok-cm commented on oci-config-examples/oci_devops_policy_dg_terraform/terraform/tenancy_scope/remote-backend_template.tf
> +    endpoint = "https://fahdabidiroottenancy.compat.objectstorage.us-ashburn-1.oraclecloud.com"
shall we mask the URL?

2022-04-22 13:24 UTC, RahulMR42 commented on oci-config-examples/oci_devops_policy_dg_terraform/README.md
> +Allow dynamic-group "<DG Name>" to manage repos in c"<Compartment Name>"
haa ,its gone over a copy ,fixed .thank you

2022-04-22 13:26 UTC, RahulMR42 commented on oci-config-examples/oci_devops_policy_dg_terraform/README.md
> +![](images/oci_project.png)
Done ,thank you

2022-04-22 13:27 UTC, RahulMR42 commented on oci-config-examples/oci_devops_policy_dg_terraform/README.md
> +- Let us do a build manual invokation.
Done ,thank you

2022-04-22 13:27 UTC, RahulMR42 commented on oci-config-examples/oci_devops_policy_dg_terraform/build_spec.yaml
> +    aws_secret_access_key: ocid1.vaultsecret.oc1.iad.amaaaaaak56z2vqa6vmu7h3ud3thzm7emsdb7fptb7zqmise2qlhx7xtehza
Done ,thank you

2022-04-22 13:29 UTC, RahulMR42 commented on oci-config-examples/oci_devops_policy_dg_terraform/compartments.config
> +mr-devops-canary=ocid1.compartment.oc1..aaaaaaaaievlqkktpe5yumlanr64gnzgi2vokbhrsuz2sddcjooewbqqj5ha
Done ,thank you

2022-04-22 13:29 UTC, RahulMR42 commented on oci-config-examples/oci_devops_policy_dg_terraform/terraform/compartment_scope/remote-backend_template.tf
> +    endpoint = "https://fahdabidiroottenancy.compat.objectstorage.us-ashburn-1.oraclecloud.com"
Done ,thank you

2022-04-22 13:29 UTC, RahulMR42 commented on oci-config-examples/oci_devops_policy_dg_terraform/terraform/compartment_scope/variables.tf
> +    default = "ocid1.tenancy.oc1..aaaaaaaasu7rvefmsyk5kqczfmdqi5clpddejfjk2attdqnk6sbk72wajq5q"
Done ,thank you

2022-04-22 13:29 UTC, RahulMR42 commented on oci-config-examples/oci_devops_policy_dg_terraform/terraform/tenancy_scope/variables.tf
> +    default = "ocid1.tenancy.oc1..aaaaaaaasu7rvefmsyk5kqczfmdqi5clpddejfjk2attdqnk6sbk72wajq5q"
Done ,thank you

2022-04-22 13:32 UTC, RahulMR42 commented on oci-config-examples/oci_devops_policy_dg_terraform/README.md
> +![](images/oci_user_1.png)
Done ,thank you

2022-04-25 04:29 UTC, ashok-cm approved these changes

2022-04-25 06:19 UTC, merged