Configs
oracle-devrel/oci-devops-examples pull request #8
Opened 2022-04-14 06:55 UTC by RahulMR42

# Description

- Devops policies and configs.
- New major sections for config.

Fixes # (issues)

New samples # (demos / Illustrations )

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

- [x] Free Tier
- [x] Always Free
- [x] Paid 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings.
- [x] All the sensitive informations are masked or removed.
- [x] All the links mentioned are valid and tested.
- [ ] Image names are seperated only with '-'.
- [x] Added instruction to clone only this sample and links to other common sample pages.

2022-04-14 09:01 UTC, ashok-cm requested changes

2022-04-14 15:32 UTC, RahulMR42 commented on oci-config-examples/oci-devops-policies-groups/README.md
> +- Use the [References](https://github.com/RahulMR42/oci-devops-policies-groups#references) section to read more about fine grain controls.
Done ,thank you..

2022-04-14 15:33 UTC, RahulMR42 commented on oci-config-examples/oci-devops-policies-groups/README.md
> +-  Create  relevenat users and all the devops users to the user group (One group is minimum).
thank you .

2022-04-15 02:02 UTC, ashok-cm approved these changes

2022-04-18 15:15 UTC, merged